/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Random;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class frm_pilas_y_colas extends javax.swing.JFrame {
    ArrayList<Integer> arreglo = new ArrayList<>();
    /**
     * Creates new form frm_pilas_y_colas
     */
    public frm_pilas_y_colas() {
        initComponents();
        this.setTitle("Pilas y Colas - Generador de Numeros Aleatorios");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generar_jbutton = new javax.swing.JButton();
        pilas_jbutton = new javax.swing.JButton();
        colas_jbutton = new javax.swing.JButton();
        lbl_anotacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setForeground(new java.awt.Color(0, 51, 255));

        generar_jbutton.setBackground(new java.awt.Color(0, 102, 51));
        generar_jbutton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        generar_jbutton.setForeground(new java.awt.Color(255, 255, 255));
        generar_jbutton.setText("Generar");
        generar_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_jbuttonActionPerformed(evt);
            }
        });

        pilas_jbutton.setBackground(new java.awt.Color(255, 51, 0));
        pilas_jbutton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pilas_jbutton.setForeground(new java.awt.Color(255, 255, 255));
        pilas_jbutton.setText("Pilas");
        pilas_jbutton.setEnabled(false);
        pilas_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilas_jbuttonActionPerformed(evt);
            }
        });

        colas_jbutton.setBackground(new java.awt.Color(0, 204, 204));
        colas_jbutton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        colas_jbutton.setText("Colas");
        colas_jbutton.setEnabled(false);
        colas_jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colas_jbuttonActionPerformed(evt);
            }
        });

        lbl_anotacion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_anotacion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_anotacion.setText("Presione el boton generar para empezar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(pilas_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(colas_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbl_anotacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(generar_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(generar_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_anotacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilas_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colas_jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generar_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_jbuttonActionPerformed

        Random aleatorio = new Random();
        //ArrayList<Integer> numeros = new ArrayList<>();
        for (int i=1; i<=1000000; i++){
            int value = aleatorio.nextInt(10000000-(-10000000)+1)+(-10000000);
            arreglo.add(value);
            //cola.add(value);
        }
        pilas_jbutton.setEnabled(true);
        colas_jbutton.setEnabled(true);
        lbl_anotacion.setVisible(false);
    }//GEN-LAST:event_generar_jbuttonActionPerformed

    private void pilas_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilas_jbuttonActionPerformed
        //Pila_mejorado :D
        Stack<Integer> pila = new Stack<Integer>();
        Iterator<Integer> itrp = arreglo.iterator(); 
        while(itrp.hasNext()){
            pila.push(itrp.next());
        }
        System.out.println("Size: " +pila.size());
        //System.out.println(pila);
        for (int i=1; i<=1000000; i++){
            pila.pop();
        }
        System.out.println("Size: " +pila.size());
        //System.out.println(pila);
        if(pila.isEmpty()){
            //System.out.println("La pila ha sido llenada y vaciada correctamente");
            JOptionPane.showMessageDialog(rootPane, "Los números han sido insertados y extraídos de la pila correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_pilas_jbuttonActionPerformed

    private void colas_jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colas_jbuttonActionPerformed
        //Cola_mejorado :D
        Queue<Integer> cola = new LinkedList<Integer>();
        Iterator<Integer> itr = arreglo.iterator(); 
        while(itr.hasNext()){
            cola.add(itr.next());
        }
        //System.out.println(arreglo+"\n");
        System.out.println("Size: " + cola.size());
        //System.out.println(cola);
        for (int i=1; i<=1000000; i++){
            cola.poll();
        }
        System.out.println("Size: " + cola.size());
        if(cola.isEmpty()){
            //System.out.println("La cola ha sido llenada y vaciada correctamente");
            JOptionPane.showMessageDialog(rootPane, "Los números han sido insertados y extraídos de la cola correctamente","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_colas_jbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_pilas_y_colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_pilas_y_colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_pilas_y_colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_pilas_y_colas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_pilas_y_colas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colas_jbutton;
    private javax.swing.JButton generar_jbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_anotacion;
    private javax.swing.JButton pilas_jbutton;
    // End of variables declaration//GEN-END:variables
}
